name: 'H-Extend'

on:
  push:
  schedule:
    # UTC (国内 UTC+8)
     - cron: '50 4 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    #runs-on: macos-latest
    runs-on: macos-12

    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
          
#        - name: 'Update Chrome'           
#          run: |
#            brew reinstall --cask google-chrome

        - name: 'Check old IP'
          run: curl -s ip.p3terx.com

#        Clash 和 WARP 二选一

#        - name: 'Install Clash'
#          run: |
#            wget https://github.com/Dreamacro/clash/releases/download/v1.11.4/clash-darwin-amd64-v1.11.4.gz
#            gunzip clash-darwin-amd64-v1.11.4.gz
#            sudo chmod +x clash-darwin-amd64-v1.11.4
#            mkdir ~/.config/clash/
#            cp clash-darwin-amd64-v1.11.4 ~/.config/clash/clash
#            cd ~/.config/clash
#            wget -O Country.mmdb https://www.sub-speeder.com/client-download/Country.mmdb
#            wget -O config.yaml ${{ secrets.CLASH_YAML }}
#            nohup ./clash -d . > /dev/null 2>&1 &
#            export all_proxy=socks5://127.0.0.1:7891
#            networksetup -setwebproxy networkservices port

        - name: 'Cloudflare WARP'
          run: |
            sudo curl -o /usr/local/bin/mac.sh https://raw.githubusercontents.com/fscarmen/warp/main/pc/mac.sh && bash mac.sh c
            
        - name: 'Check New IP'
          run: curl -s ip.p3terx.com

        - name: 'Install requirements'
          run: |
            pip3 install -r VPS/requirements.txt
            pip3 install undetected-chromedriver
            yes | pip3 uninstall selenium
            pip3 install selenium==4.2.0
            
#        - name: 'Random sleep'
#          run: |
#            sleep $[ ( $RANDOM % 100 )  + 1 ]

        - name: 'Renew'
          env:
            USER_ID: ${{ secrets.USER_ID }}
            PASS_WD: ${{ secrets.PASS_WD }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
          run: |
            python3 VPS/main-h.py
